###
POST  http://192.168.31.179:8080/accounts/ HTTP/1.1
Content-Type: application/json

{
    "owner": "Jia/",
    "currency": "EUR"
}

###
GET  http://192.168.31.179:8080/accounts/1 HTTP/1.1

###
GET  http://192.168.31.179:8080/accounts?page_id=1&page_size=7 HTTP/1.1

###
PATCH   http://192.168.31.179:8080/accounts/1 HTTP/1.1
Content-Type: application/json

{
    "balance": 0
}