###
POST  http://localhost:8080/accounts/ HTTP/1.1
Content-Type: application/json

{
    "owner": "xstgtr",
    "currency": "CAD"
}

###
GET  http://localhost:8080/accounts/1 HTTP/1.1

###
GET  http://localhost:8080/accounts?page_id=1&page_size=7 HTTP/1.1

###
PATCH   http://localhost:8080/accounts/1 HTTP/1.1
Content-Type: application/json

{
    "balance": 0
}

###
DELETE http://localhost:8080/accounts/1 HTTP/1.1

###
POST http://localhost:8080/transfers HTTP/1.1
Content-Type: application/json

{
    "from_account_id": 62,
    "to_account_id": 63,
    "amount": 35,
    "currency": "CAD"
}

###
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "username": "LiHuahua",
    "password":"456",
    "full_name":"Ding Zhen",
    "email":"1008@gmail.com"
}