name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build image to ACR
        run: |
          docker build . -t contoso.azurecr.io/simplebank:${{ github.sha }}
          docker push contoso.azurecr.io/simplebank:${{ github.sha }}  